export const ADVENTURE_SOLUTION = {
  toSignalComputer: 'RRDDDDRRUURRUULLRRRRDDRRRRUUL',
  signalAnswer: 'ORBIT',
  signalToArchiveComputer: 'RRRDDRRDDRRUUUULLRRDDDDDDLLDDLLDDDDRRDDDDLLLLDDRRRRRRUUUUUUUULLRRUUDDDDDDDDDDLLLLLLLLUUUUUULLLLDDDDLLUUUUUURRUURRRRDDLRRRDDDDR',
  archiveAnswer: 'GLYPH',
  archiveToFinalGate: 'LUUUUUUUULLUURRRRDDUULLLLLLLLDDRRLLLLDDLLDDDDDDDDDDRRRRRRUUUUDDDDLLLLLLLLUUUUUUUUUUUURRLLUUU',
  finalPortalStep: 'U',
  expectedMoves: 248,
} as const;
