import { CLASSIC_LABS } from '../lab/classicLabs';
import { MOTION_LABS } from '../lab/motionLabs';
export type GameId = 'adventure' | 'block-shift' | 'mine-trail' | number;
export type Category = 'All games' | 'Think' | 'React' | 'Remember' | 'Explore';
export interface GameInfo { id: GameId; title: string; category: Category; description: string; instructions: string; tip: string; minutes: string; color: string; art: number; difficulty: string }
const categories: Record<number, Category> = {3:'Explore',4:'React',5:'React',6:'React',7:'React',8:'Think',9:'Think',10:'Explore',11:'Think',12:'Remember',13:'Think',14:'React',15:'Think',16:'Think',17:'Think',18:'Think',19:'Think',20:'Think',21:'Think',22:'Think',23:'Think',24:'Think',25:'Think',26:'Think'};
const tips: Record<number,string> = {
3:'Clear one branch at a time. Watch the shades at intersections; you have three chances.',4:'Leave a narrow well for long pieces. Up rotates; Space drops immediately.',5:'The moss strip is a safe place to wait. Watch a full lane cycle before hopping.',6:'Plan a wide loop. A queued turn takes effect at the next tile; avoid sharp reversals.',7:'Drag anywhere on the playfield to aim the paddle. Meet the ball early; the edges change its angle.',8:'Keep your strongest rune in one corner and build toward it.',9:'Each tap flips a cross. Tapping the same tile twice cancels the change.',10:'You stop only at walls. Work backward from each sigil.',11:'Plan where you will stand after a push. Undo is your friend.',12:'Say the pad numbers aloud. A mistake lets you watch the sequence again.',13:'Match each pipe to its pale blueprint. Four taps restore its original orientation.',14:'Wait for the bright moving marker to enter the target arc, then pulse.',15:'Green means the right place; gold means a different place; gray means absent. Repeated letters matter.',16:'Look for the tightest connection first. “One away” means three of your four words belong together.',17:'Read the scan clues around the board, mark three candidate prisms, then submit.',18:'Each island needs two links, and all islands must belong to one network.',19:'Start at the upper-left pool. Choose a color that reaches more than one neighboring region.',20:'The star is the center of its region. Opposite tiles should match around that center.',21:'A jump needs an occupied middle socket and an empty landing. Avoid leaving isolated pegs.',22:'Match equal neighbors. Each tile belongs to exactly one pair.',23:'Use each height once in every row and column. Follow the inequality marks.',24:'Begin at the marked start. Every arrow points toward the next tile in the route.',25:'Balance each row and keep neighboring poles opposite.',26:'Swap two nodes to untangle the lines. Start with the longest crossing.'};
const colors = ['#e8bc64','#85b8a1','#85b9cf','#b29bcc','#dd977c','#a1b970'];
export const GAMES: GameInfo[] = [
{id:'adventure',title:'Venture Circuit',category:'Explore',description:'A little world with a lot of secrets.',instructions:'Collect ten chips, find both keys and protective boots, solve two computer terminals, then power the gate with the crate.',tip:'Explore each branch before returning to the center. Stand next to a computer and press USE. Gates stay open once unlocked.',minutes:'10–20',color:'#8cab7d',art:0,difficulty:'An adventure'},
{id:'block-shift',title:'Block Shift',category:'Think',description:'Make room for a brilliant escape.',instructions:'Walk behind the blocks to push them along their rails. Slide the relic cart to the exit. Undo any move to rethink your route.',tip:'Clear the long service beam first. A block only moves along its marked axis.',minutes:'5–10',color:'#d6ad75',art:1,difficulty:'Challenging'},
{id:'mine-trail',title:'Mine Trail',category:'Think',description:'Every number tells a little secret.',instructions:'Guide your explorer across the tiles. Reveal with ACTION; numbers count mines in the eight surrounding squares. Reveal all safe tiles.',tip:'Start with the revealed clue. Movement alone is safe; a tile is tested only when you reveal it.',minutes:'3–5',color:'#a4b780',art:2,difficulty:'Thoughtful'},
...[...CLASSIC_LABS,...MOTION_LABS].map(lab=>({id:lab.id,title:lab.title,category:categories[lab.id],description:({3:'Gather the glow. Outwit the shadows.',4:'A sky-high game of perfect fits.',5:'One brave hop at a time.',6:'Follow your own electric footsteps.',7:'A kaleidoscope waiting to happen.',8:'Small matches. Magical combinations.',9:'Find the spark that lights it all.',10:'A slippery path to a clever ending.',11:'A satisfying push in the right direction.',12:'A little rhythm for your memory.',13:'Turn a tangle into a connection.',14:'Take a breath. Find your moment.',15:'Five letters. One lovely revelation.',16:'Unexpected things belong together.',17:'Follow the light to hidden treasures.',18:'Bring a scattered world together.',19:'Make a splash. Change everything.',20:'A constellation of perfect symmetry.',21:'One leap closer to the last relic.',22:'Find a partner for every little rune.',23:'Let a city of logic rise.',24:'Find the thread that connects it all.',25:'A puzzle of irresistible opposites.',26:'Give a tangled constellation some space.'} as Record<number,string>)[lab.id],instructions:lab.objective,tip:tips[lab.id],minutes:lab.id===12||lab.id===14?'1–2':'2–5',color:colors[lab.id%colors.length],art:lab.id,difficulty:lab.id>=17?'Thoughtful':categories[lab.id]==='React'?'Quick reflexes':'Curious minds'}))
];
export const gameInfo = (id: GameId) => GAMES.find(g=>g.id===id) ?? GAMES[0];
export function dateKey(date = new Date()) { return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`; }
export function daySeed(key: string) { return [...key].reduce((n,c)=>(Math.imul(n,31)+c.charCodeAt(0))>>>0,0); }
export function dailyRoute(key: string): GameId[] { const n=daySeed(key); return [[19,22,9][n%3],12,[13,18,26][n%3],14,[15,16][n%2]]; }
