import { lazy, Suspense, useCallback, useEffect, useRef, useState, type CSSProperties, type ReactNode } from 'react';
import { CharacterCustomizer, CharacterPortrait } from '../character/CharacterCustomizer';
import { loadCharacterCustomization, saveCharacterCustomization, type CharacterCustomization } from '../character/character';
import { GAMES, dailyRoute, dateKey, daySeed, gameInfo, type Category, type GameId, type GameInfo } from './catalog';
import { Compass, GameArt, IslandArt } from './Art';
import { loadPassport, savePassport, recordWin, prettyTime, type Passport } from './storage';
import { gameFeedback, setGamePaused, setGameSound } from './runtime';
const ClassicLab=lazy(()=>import('../lab/ClassicLab').then(m=>({default:m.ClassicLab})));
const MotionLab=lazy(()=>import('../lab/MotionLab').then(m=>({default:m.MotionLab})));
const AdventureLab=lazy(()=>import('../lab/AdventureLab').then(m=>({default:m.AdventureLab})));
const BlockShiftLab=lazy(()=>import('../lab/BlockShiftLab').then(m=>({default:m.BlockShiftLab})));
const MineTrailLab=lazy(()=>import('../lab/MineTrailLab').then(m=>({default:m.MineTrailLab})));
const LegacyApp=lazy(()=>import('../App').then(m=>({default:m.App})));
const FormulaPreview=lazy(()=>import('../lab/FormulaPreview').then(m=>({default:m.FormulaPreview})));

type View='discover'|'arcade'|'passport';
function initialGame():GameId|null { const query=new URLSearchParams(location.search); if(query.get('daily')===dateKey()){const index=Math.max(0,loadPassport().daily[dateKey()]||0);return dailyRoute(dateKey())[index]??null;} const v=query.get('lab'); if(v==='adventure'||v==='block-shift'||v==='mine-trail')return v; const n=Number(v); return n>=3&&n<=26?n:null; }
function Dialog({title,close,children}:{title:string;close:()=>void;children:ReactNode}){
 const ref=useRef<HTMLElement>(null);
 useEffect(()=>{const old=document.activeElement as HTMLElement;ref.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.stopPropagation();close();}if(e.key==='Tab'){const nodes=ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,a[href],[tabindex="0"]');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key,true);return()=>{document.removeEventListener('keydown',key,true);old?.focus();};},[close]);
 return <div className="v-dialog-backdrop" onPointerDown={e=>{if(e.target===e.currentTarget)close();}}><section ref={ref} tabIndex={-1} className="v-dialog" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="v-icon" onClick={close} aria-label="Close dialog">×</button></header>{children}</section></div>;
}
function GameCard({game,open,saved,favorite,toggle}:{game:GameInfo;open:()=>void;saved:boolean;favorite:boolean;toggle:()=>void}){return <article className="v-game-card" style={{'--card-color':game.color} as CSSProperties}><button className="v-card-play" onClick={open} aria-label={`Play ${game.title}`}><div className="v-card-art"><GameArt type={game.art} color={game.color}/><span className="v-category">{game.category}</span>{saved&&<span className="v-earned" title="Stamp collected">✓</span>}</div><div className="v-card-body"><h3>{game.title}<span>↗</span></h3><p>{game.description}</p><div className="v-card-meta"><span>◷ {game.minutes} min</span><span>{game.difficulty}</span></div></div></button><button className={`v-favorite ${favorite?'active':''}`} onClick={toggle} aria-label={`${favorite?'Unsave':'Save'} ${game.title}`} aria-pressed={favorite}>{favorite?'♥':'♡'}</button></article>}

function PlayRoom({id,character,onExit,onComplete,passport,changePassport,daily,index}:{id:GameId;character:CharacterCustomization;onExit:()=>void;onComplete:(ms:number)=>void;passport:Passport;changePassport:(p:Passport)=>void;daily:boolean;index:number}){
 const info=gameInfo(id); const [ready,setReady]=useState(false); const [paused,pause]=useState(false); const [round,setRound]=useState(0); const [help,setHelp]=useState(false); const activeMs=useRef(0); const done=useRef(false);
 const complete=useCallback(()=>{if(done.current)return;done.current=true;gameFeedback(true);onComplete(Math.max(1000,activeMs.current));},[onComplete]);
 useEffect(()=>{activeMs.current=0;done.current=false;setGamePaused(false);return()=>setGamePaused(false);},[id,round]);
 useEffect(()=>{setGamePaused(!ready||paused||help);return()=>setGamePaused(false);},[paused,help,ready]);
 useEffect(()=>{const timer=setInterval(()=>{if(ready&&!paused&&!help&&!document.hidden&&!done.current)activeMs.current+=100;},100);return()=>clearInterval(timer);},[paused,help,ready]);
 useEffect(()=>{const visibility=()=>{if(document.hidden)pause(true);};const keyboard=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();if(help)setHelp(false);else if(ready)pause(v=>!v);}else if(!ready||paused||help){e.stopImmediatePropagation();}else if(e.key.toLowerCase()==='f'&&id!==15&&!(id==='adventure'&&document.querySelector('.adventure-computer-panel'))){if(document.fullscreenElement)void document.exitFullscreen?.().catch(()=>{});else void document.documentElement.requestFullscreen?.().catch(()=>{});}};document.addEventListener('visibilitychange',visibility);window.addEventListener('keydown',keyboard,true);return()=>{document.removeEventListener('visibilitychange',visibility);window.removeEventListener('keydown',keyboard,true);};},[paused,help,ready,id]);
 const closeHelp=useCallback(()=>setHelp(false),[]);
 const props={character,onExit,onComplete:complete};
 return <div className="v-play-page"><div className="v-play-top"><button onClick={onExit}>← All games</button><span>{daily?`TODAY’S EXPEDITION · ROOM ${index+1} / 5`:'A LITTLE TIME WELL SPENT'}</span><button onClick={()=>pause(true)} aria-label="Pause game">Ⅱ <span>Pause</span></button></div><div className="v-play-layout"><aside className="v-field-notes"><span className="v-kicker">THE FIELD GUIDE / {info.category.toUpperCase()}</span><h1>{info.title}</h1><p>{info.description}</p><div className="v-note-art"><GameArt type={info.art} color={info.color}/></div><h3>Your mission</h3><p>{info.instructions}</p><h3>A little nudge</h3><p>{info.tip}</p><div className="v-note-controls">Play with touch or a mouse.<br/>Arrow keys / WASD to move.<br/>Escape to pause.</div>{passport.records[String(id)]&&<div className="v-personal-best">✦ PERSONAL BEST <b>{prettyTime(passport.records[String(id)].bestMs)}</b></div>}</aside><div className="v-play-device"><div className="phone-stage"><Suspense fallback={<div className="v-loading">Opening your little escape…</div>}><div key={`${id}-${round}`}>
{id==='adventure'?<AdventureLab {...props}/>:id==='block-shift'?<BlockShiftLab {...props}/>:id==='mine-trail'?<MineTrailLab {...props}/>:id<=16?<ClassicLab {...props} seed={daily?daySeed(dateKey()):0} id={id as import('../lab/classicLabs').ClassicLabId} contextLabel={daily?`EXPEDITION · ROOM ${index+1} OF 5`:'THE PUZZLE ARCADE'}/>:<MotionLab {...props} id={id as import('../lab/motionLabs').MotionLabId}/>}
</div></Suspense>{!ready&&<div className="v-pause v-ready" role="dialog" aria-modal="true" aria-label="Ready to play"><div className="v-ready-art"><GameArt type={info.art} color={info.color}/></div><span className="v-kicker">{daily?`EXPEDITION · ROOM ${index+1} OF 5`:info.category.toUpperCase()}</span><h2>{info.title}</h2><p>{info.instructions}</p><button className="v-primary" onClick={()=>setReady(true)}>Let’s play →</button><small>Touch to play · Escape to pause</small></div>}{paused&&<div className="v-pause" role="dialog" aria-modal="true" aria-label="Game paused"><Compass size={56}/><span className="v-kicker">TAKE YOUR TIME</span><h2>A little breather.</h2><p>Your game is paused. The world can wait.</p><button className="v-primary" onClick={()=>pause(false)}>Keep exploring →</button><button className="v-secondary" onClick={()=>{pause(false);setHelp(true);}}>How to play</button><button className="v-secondary" onClick={()=>{setRound(n=>n+1);pause(false);}}>Restart this room</button><button className="v-secondary" onClick={()=>changePassport({...passport,sound:!passport.sound})}>Sound {passport.sound?'on':'off'}</button><button className="v-text" onClick={onExit}>Return to the arcade</button></div>}</div><div className="v-play-tools"><button onClick={()=>setHelp(true)}>ⓘ How to play</button>{[8,9,10,11,13,17,18,19,20,21,22,23,24,25,26].includes(Number(id))&&<button onClick={()=>window.dispatchEvent(new Event('venture-undo'))}>↶ Undo move</button>}<button onClick={()=>pause(true)}>Ⅱ Pause</button></div></div><aside className="v-play-right"><span className="v-kicker">YOUR LITTLE ESCAPE</span><div className="v-mini-compass"><Compass size={64}/></div><h3>{daily?'Five rooms. One adventure.':'Curiosity looks good on you.'}</h3><p>{daily?'Finish each room and walk through its portal. Your place is saved between rooms.':'Solve the puzzle, celebrate, then guide your explorer into the portal to collect your stamp.'}</p>{daily&&<div className="v-route-dots">{[0,1,2,3,4].map(i=><span key={i} className={i<=index?'done':''}>{i<index?'✓':i+1}</span>)}</div>}<p className="v-muted">No timer pressure for puzzle rooms. Try, undo, and discover.</p></aside></div>{help&&<Dialog title={info.title} close={closeHelp}><div className="v-help-art"><GameArt type={info.art} color={info.color}/></div><h3>Your mission</h3><p>{info.instructions}</p><h3>A little nudge</h3><p>{info.tip}</p><p>When the portal opens, use the arrows or swipe to walk into it and collect your stamp.</p><button className="v-primary" onClick={closeHelp}>Let’s play →</button></Dialog>}</div>;
}
export function VentureApp(){
const params=new URLSearchParams(location.search);
const [view,setView]=useState<View>('discover');const [selected,select]=useState<GameId|null>(initialGame);const [passport,setPassport]=useState(loadPassport);const [character,setCharacter]=useState(loadCharacterCustomization);const [modal,setModal]=useState<'install'|'character'|'settings'|null>(null);const [category,setCategory]=useState<Category>('All games');const [search,setSearch]=useState('');const [savedOnly,setSavedOnly]=useState(false);const [daily,setDaily]=useState(()=>params.get('daily')===dateKey());const [result,setResult]=useState<{id:GameId;ms:number}|null>(null);const [offline,setOffline]=useState(!navigator.onLine);const [installEvent,setInstallEvent]=useState<Event & {prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>}|null>(null);
const [today]=useState(dateKey);const route=dailyRoute(today);const dailyIndex=Math.min(5,Math.max(0,passport.daily[today]||0));
const changePassport=useCallback((p:Passport)=>{setPassport(p);savePassport(p);},[]);
const closeModal=useCallback(()=>setModal(null),[]);
useEffect(()=>{setGameSound(passport.sound);document.documentElement.classList.toggle('v-reduce-motion',passport.reducedMotion);},[passport.sound,passport.reducedMotion]);
useEffect(()=>{const online=()=>setOffline(!navigator.onLine);const install=(e:Event)=>{e.preventDefault();setInstallEvent(e as typeof installEvent);};window.addEventListener('online',online);window.addEventListener('offline',online);window.addEventListener('beforeinstallprompt',install);return()=>{window.removeEventListener('online',online);window.removeEventListener('offline',online);window.removeEventListener('beforeinstallprompt',install);};},[]);
useEffect(()=>{if(selected!==null||params.has('legacy')||params.get('lab')==='formula')return;window.render_game_to_text=()=>JSON.stringify({mode:'venture-hub',view,selectedCategory:category,gameCount:GAMES.length,daily:{date:today,route,completed:dailyIndex},stamps:Object.keys(passport.records).length,coordinateSystem:'responsive document; origin top-left, x right, y down'});window.advanceTime=()=>{};},[selected,view,category,passport,today,dailyIndex]);
const navigate=(next:View)=>{setView(next);select(null);setResult(null);setDaily(false);history.replaceState(null,'',location.pathname);window.scrollTo(0,0);};
const openGame=(id:GameId,isDaily=false)=>{setResult(null);setDaily(isDaily);select(id);history.replaceState(null,'',`${location.pathname}?lab=${id}${isDaily?`&daily=${today}`:''}`);window.scrollTo(0,0);};
const finish=useCallback((ms:number)=>{if(selected===null)return;history.replaceState(null,'',location.pathname);let next=recordWin(passport,selected,ms,today);if(daily)next={...next,daily:{...next.daily,[today]:Math.min(5,dailyIndex+1)}};changePassport(next);setResult({id:selected,ms});select(null);},[selected,passport,today,daily,dailyIndex,changePassport]);
const toggleFavorite=(id:GameId)=>{const key=String(id);changePassport({...passport,favorites:passport.favorites.includes(key)?passport.favorites.filter(s=>s!==key):[...passport.favorites,key]});};
const allFiltered=GAMES.filter(g=>(category==='All games'||g.category===category)&&(!savedOnly||passport.favorites.includes(String(g.id)))&&`${g.title} ${g.description} ${g.category}`.toLowerCase().includes(search.toLowerCase()));
const featured=[GAMES.find(g=>g.id===1)||GAMES[1],gameInfo(12),gameInfo(15),gameInfo(19),gameInfo(14),gameInfo(26)];
const stamps=Object.keys(passport.records).length;
if(params.has('legacy'))return <Suspense fallback={<div className="v-loading">Opening the story archive…</div>}><LegacyApp/></Suspense>;
if(params.get('lab')==='formula')return <div className="app"><div className="phone-stage"><Suspense fallback={null}><FormulaPreview character={character} onExit={()=>location.assign(location.pathname)}/></Suspense></div></div>;
if(selected!==null)return <PlayRoom key={String(selected)} id={selected} character={character} onExit={()=>navigate('arcade')} onComplete={finish} passport={passport} changePassport={changePassport} daily={daily} index={dailyIndex}/>;
return <div className="v-app"><header className="v-header"><button className="v-brand" onClick={()=>navigate('discover')} aria-label="Daily Venture home"><Compass/><span>daily venture<span className="v-brand-dot">.</span></span></button><nav aria-label="Main navigation">{(['discover','arcade','passport'] as View[]).map(v=><button key={v} className={view===v?'active':''} onClick={()=>navigate(v)}>{v==='discover'?'Discover':v==='arcade'?'The arcade':'My passport'}</button>)}</nav><div className="v-header-right"><button className="v-stamp-total" onClick={()=>navigate('passport')}>✦ <span>{stamps} stamps</span></button><button className="v-avatar" onClick={()=>setModal('character')} aria-label={`Customize character, ${character.name}`}><CharacterPortrait character={character}/></button><button className="v-icon v-settings" onClick={()=>setModal('settings')} aria-label="Settings">⚙</button></div></header>
<main className="v-main">{offline&&<div className="v-offline">You’re offline. Your downloaded little escapes are still here.</div>}
{result?<section className="v-result"><div className="v-result-stamp">✦</div><span className="v-kicker">{daily&&dailyIndex===5?'EXPEDITION COMPLETE':'A NEW MEMORY FOR YOUR PASSPORT'}</span><h1>{daily&&dailyIndex===5?'Five rooms. Beautifully done.':'Curiosity, rewarded.'}</h1><p>You cleared {gameInfo(result.id).title} in {prettyTime(result.ms)}.<br/>{daily?`${dailyIndex} of 5 rooms explored. Your progress is saved.`:'Your stamp and personal best are saved on this device.'}</p><div className="v-result-art"><GameArt type={gameInfo(result.id).art} color={gameInfo(result.id).color}/></div><button className="v-primary" onClick={()=>daily&&dailyIndex<5?openGame(route[dailyIndex],true):navigate('arcade')}>{daily&&dailyIndex<5?'On to the next room →':'Find your next escape →'}</button><button className="v-text" onClick={()=>openGame(result.id)}>Play this room again</button></section>:<>
{view==='discover'&&<><div className="v-welcome"><span>THE EVERYDAY ADVENTURE CLUB</span><span>{new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})} <i>✧</i></span></div><section className="v-hero"><div className="v-hero-copy"><div className="v-live-label"><span/> A LITTLE WONDER, EVERY DAY</div><h1>Little escapes.<br/>Big <em>discoveries.</em></h1><p>A curious collection of puzzles, playful worlds,<br className="v-desktop-break"/> and “just one more try” moments.</p><button className="v-primary" onClick={()=>dailyIndex>=5?navigate('passport'):openGame(route[dailyIndex],true)}>{dailyIndex>=5?'Today’s expedition complete ✓':dailyIndex?'Continue today’s adventure':'Start today’s adventure'} <span>→</span></button><div className="v-hero-caption"><span>5 handpicked rooms</span><i>·</i><span>At your own pace</span><i>·</i><span>Free to explore</span></div></div><div className="v-hero-world"><IslandArt/><div className="v-world-tag"><span>✦</span><div>THE VERDANT ISLES<small>There’s wonder around every corner.</small></div></div></div><span className="v-hero-number">EST. FOR CURIOUS MINDS</span></section>
<section className="v-expedition-strip"><div className="v-expedition-title"><span className="v-route-symbol">⌁</span><div><strong>Your daily expedition</strong><p>Five small challenges. One satisfying journey.</p></div></div><div className="v-mini-route">{route.map((id,i)=><button key={i} className={i<dailyIndex?'complete':i===dailyIndex?'current':''} onClick={()=>i<=dailyIndex&&dailyIndex<5?openGame(route[dailyIndex],true):undefined} disabled={i>dailyIndex||dailyIndex===5} aria-label={`Room ${i+1}: ${gameInfo(id).title}${i<dailyIndex?', completed':''}`}><span>{i<dailyIndex?'✓':i+1}</span><small>{gameInfo(id).title}</small></button>)}</div><span className="v-route-count">{dailyIndex}<small> / 5</small></span></section>
<div className="v-section-heading"><div><span className="v-kicker">FOLLOW YOUR CURIOSITY</span><h2>Find your kind of fun.</h2></div><button className="v-text" onClick={()=>navigate('arcade')}>Explore all {GAMES.length} games <span>↗</span></button></div><div className="v-card-grid">{featured.map(g=><GameCard key={g.id} game={g} open={()=>openGame(g.id)} saved={!!passport.records[String(g.id)]} favorite={passport.favorites.includes(String(g.id))} toggle={()=>toggleFavorite(g.id)}/>)}</div>
<section className="v-adventure-banner"><div className="v-adventure-art"><IslandArt/></div><div><span className="v-kicker">WHEN YOU WANT TO GET A LITTLE LOST</span><h2>A whole world to figure out.</h2><p>Hidden paths. Curious computers. A maze full of small revelations.<br/>Meet Venture Circuit, your next proper adventure.</p><button className="v-secondary" onClick={()=>openGame('adventure')}>Enter Venture Circuit ↗</button></div><span className="v-banner-badge">EXPLORE<br/><b>✧</b><br/>DISCOVER</span></section>
<section className="v-install-strip"><Compass size={46}/><div><h3>Your pocket-sized happy place.</h3><p>Add Daily Venture to your home screen. A little escape, always a tap away.</p></div><button className="v-secondary" onClick={()=>setModal('install')}>Add to home screen ↗</button></section></>}
{view==='arcade'&&<><div className="v-page-intro"><span className="v-kicker">27 WAYS TO FOLLOW YOUR CURIOSITY</span><h1>The puzzle arcade.</h1><p>Find your flow. Train your brain. Or just play something lovely.</p></div><div className="v-arcade-toolbar"><div className="v-filters" aria-label="Game categories">{(['All games','Think','React','Remember','Explore'] as Category[]).map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><label className="v-search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a little escape…" aria-label="Search games"/></label></div><div className="v-list-caption"><span>{allFiltered.length} games to get lost in</span><button className={savedOnly?'active':''} onClick={()=>setSavedOnly(v=>!v)} aria-pressed={savedOnly}>♡ Saved games {savedOnly?'✓':''}</button></div><div className="v-card-grid arcade">{allFiltered.map(g=><GameCard key={g.id} game={g} open={()=>openGame(g.id)} saved={!!passport.records[String(g.id)]} favorite={passport.favorites.includes(String(g.id))} toggle={()=>toggleFavorite(g.id)}/>)}</div>{!allFiltered.length&&<div className="v-empty"><h2>No escapes found, yet.</h2><p>Try another search or category.</p><button className="v-secondary" onClick={()=>{setSearch('');setCategory('All games');setSavedOnly(false);}}>Show every game</button></div>}</>}
{view==='passport'&&<><div className="v-page-intro"><span className="v-kicker">A JOURNAL OF SMALL DISCOVERIES</span><h1>{character.name}’s passport.</h1><p>Every solved puzzle leaves a little mark. Collect all {GAMES.length} stamps.</p></div><div className="v-passport-stats"><div><b>{stamps}<small> / {GAMES.length}</small></b><span>unique stamps</span></div><div><b>{Object.values(passport.records).reduce((n,r)=>n+r.wins,0)}</b><span>rooms explored</span></div><div><b>{Object.values(passport.daily).filter(n=>n>=5).length}</b><span>daily expeditions</span></div></div><div className="v-stamp-grid">{GAMES.map(g=>{const record=passport.records[String(g.id)];return <button key={g.id} className={record?'earned':''} onClick={()=>openGame(g.id)}><div><span>{record?'✦':'◇'}</span><small>{g.category.toUpperCase()}</small></div><h3>{g.title}</h3><p>{record?`Best ${prettyTime(record.bestMs)} · ${record.wins} cleared`:'A discovery waiting to happen'}</p></button>})}</div><p className="v-storage-note">Your passport, saved games, and explorer stay on this device. No account needed.</p></>}
</>}
<footer className="v-footer"><div><Compass size={24}/><span>A little play goes a long way.</span></div><button onClick={()=>location.assign(`${import.meta.env.BASE_URL}?legacy=1`)}>Original story adventures ↗</button><button onClick={()=>setModal('install')}>Take it with you ↗</button><button onClick={()=>setModal('settings')}>Settings</button><small>MADE FOR CURIOUS MINDS</small></footer></main>
{modal==='install'&&<Dialog title="Your next escape, one tap away." close={closeModal}><Compass size={66}/><p>Make room for a little wonder on your home screen.</p><ol className="v-install-steps"><li><b>Open in Safari on your iPhone.</b><span>Use this game’s web address.</span></li><li><b>Tap Share, then Add to Home Screen.</b><span>You may need to scroll down the share menu.</span></li><li><b>Keep “Open as Web App” on, then tap Add.</b><span>Launch from your new Daily Venture icon.</span></li></ol><p className="v-note">After the first online visit finishes downloading, the arcade works offline. Your passport stays on this device.</p>{installEvent&&<button className="v-primary" onClick={async()=>{await installEvent.prompt();await installEvent.userChoice;setInstallEvent(null);}}>Install Daily Venture</button>}<a className="v-source-link" href="https://support.apple.com/guide/iphone/iphea86e5236/ios" target="_blank" rel="noreferrer">Apple’s home-screen guide ↗</a></Dialog>}
{modal==='character'&&<Dialog title="Meet your explorer." close={closeModal}><CharacterCustomizer character={character} onSave={(next)=>{setCharacter(saveCharacterCustomization(next));}}/></Dialog>}
{modal==='settings'&&<Dialog title="Make yourself at home." close={closeModal}><div className="v-setting"><div><b>Playful little sounds</b><p>Soft notes for moves and discoveries.</p></div><button onClick={()=>changePassport({...passport,sound:!passport.sound})} aria-pressed={passport.sound}>{passport.sound?'On':'Off'}</button></div><div className="v-setting"><div><b>Less motion</b><p>A calmer journey through the menus.</p></div><button onClick={()=>changePassport({...passport,reducedMotion:!passport.reducedMotion})} aria-pressed={passport.reducedMotion}>{passport.reducedMotion?'On':'Off'}</button></div><p className="v-note">Games pause when you switch away. Daily expedition progress is saved after each completed room.</p><button className="v-secondary" onClick={()=>setModal('install')}>Add to home screen ↗</button></Dialog>}
</div>;
}
