import { mkdir, writeFile } from 'node:fs/promises';
import { WEEK_ONE } from '../src/content/week1';

const escape = (value: string) => value.replaceAll("'", "''");
const rows = WEEK_ONE.map((item) => `('${escape(item.id)}', ${item.weekIndex}, '${item.status}', null, '${escape(item.title)}', '${escape(item.subtitle)}', '${escape(JSON.stringify(item))}'::jsonb)`).join(',\n');
const sql = `-- Generated by npm run content:seed. Do not hand-edit adventure JSON.\ninsert into public.adventures(id, week_index, status, publish_date, title, subtitle, content) values\n${rows}\non conflict (id) do update set week_index = excluded.week_index, status = excluded.status, title = excluded.title, subtitle = excluded.subtitle, content = excluded.content, updated_at = now();\n`;
await mkdir(new URL('../supabase/', import.meta.url), { recursive: true });
await writeFile(new URL('../supabase/seed.sql', import.meta.url), sql);
console.log(`Wrote ${WEEK_ONE.length} adventures to supabase/seed.sql`);
